create_azure_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
  output_file: outputs/azure_architecture.md
  agent: azure_architect

create_aws_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
  output_file: outputs/aws_architecture.md
  agent: aws_architect

create_gcp_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
  output_file: outputs/gcp_architecture.md
  agent: gcp_architect

decide_best_architectures:
  description: >
    Decide the best architecture for the requirements provided by the azure_architect, aws_architect, gcp_architect : {requirements}
    Don't give any other information just the best architecture and justify the choice
  expected_output: >
    A list of the best architecture for the requirements : {requirements}
  output_file: outputs/best_architectures.md
  agent: head_architect