create_azure_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
    The architecture should cover all requirements provided.
    For each requirement, provide an explanation of the architecture and the services used to implement the requirement.
  output_file: outputs/azure_architecture.md
  agent: azure_architect

create_aws_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
    The architecture should cover all requirements provided.
    For each requirement, provide an explanation of the architecture and the services used to implement the requirement.
  output_file: outputs/aws_architecture.md
  agent: aws_architect

create_gcp_architecture:
  description: >
    Create a detailed architecture for the requirements : {requirements}
  expected_output: >
    A detailed architecture for the requirements : {requirements}
    The architecture should cover all requirements provided.
    For each requirement, provide an explanation of the architecture and the services used to implement the requirement.
  output_file: outputs/gcp_architecture.md
  agent: gcp_architect

decide_best_architecture:
  description: >
    Decide the best solution for the requirements provided by the azure_architect, aws_architect, gcp_architect : {requirements}
  expected_output: >
    Decisision on the best solution with the justification for the choice.
    output_file: outputs/architecture_decision.md
  agent: head_architect
  context:
    - create_azure_architecture
    - create_aws_architecture
    - create_gcp_architecture
